#Basic Yaml file

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx


#For ReplicaSet

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      batch: c42
  template:
    metadata:
      name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx


#For Deployment of vote app

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 3
  selector:
    matchLabels:
      batch: vote
  template:
    metadata:
      name: vote
      labels: 
        app: vote
    spec:
      containers:
      - name: vote
        image: dipesh017/demo:vote
---
appversion: v1
kind: Service 
metadata:
  name: vote
spec:
  type: LoadBalancer
  ports:
    port: 80
  selector:
    app: vote        

#For Redis

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
  selector:
    app: redis


#Deployment of Nginx Server

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: nginx


# For resource & request

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 15
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      name: vote
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: dipesh017/demo:vote
        resources:
          requests:
            cpu: ".2"
            memory: "256Mi"
          limits:
            cpu: "2"
            memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: vote
    